name: 发送 Telegram 通知

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  notify:
    name: 发送 Telegram 通知
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    steps:
      - name: Send Telegram message
        shell: bash
        run: |
          set -euo pipefail

          NEW_TAG="${GITHUB_REF_NAME}"

          TEXT=$(cat <<EOF
          <b>New Release Pushed:</b>
          
          Branch: main
          Release Tag: <code>${NEW_TAG}</code>
          
          Features: 
          <pre>ReSukiSU = true
          SuSFS = true
          BBG=false
          LZ4KD = false
          Built-in KPM = false
          KPatch-Next Support =true</pre>
          Change Log: 
          <pre>Nothing Changed
          Nothing Changed
          </pre>
          Download: <a href="https://github.com/coolzyd9107/GKI_KernelSU_SUSFS/releases/tag/${NEW_TAG}">Click Here</a>
          EOF
          )

          curl -s "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d parse_mode="HTML" \
            -d text="${TEXT}"
