name: 发送 Telegram 通知 (测试)

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit (sha 或描述)"
        required: true
        type: string
      change_log:
        description: "Change log"
        required: true
        type: string

permissions:
  contents: write

jobs:
  notify:
    name: 发送 Telegram 群组通知
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          message_thread_id: ${{secrets.message_thread_id}}
        run: |
          set -euo pipefail

          INPUT_COMMIT="${{ inputs.commit }}"
          INPUT_CHANGE_LOG="${{ inputs.change_log }}"

          TEXT=$(cat <<EOF
          <b>New GKI Release:</b>
          
          Branch: <code>main</code>
          Commit: ${INPUT_COMMIT}
          Tag: <code>${NEW_TAG}</code>
          
          Features: 
          <pre>ReSukiSU = ${{ inputs.kernelsu_variant == 'ReSukiSU' && 'true' || 'false' }}
          SuSFS = ${{ inputs.cancel_susfs && 'false' || 'true' }}
          BBG = ${{ inputs.use_bbg && 'true' || 'false' }}
          LZ4KD = ${{ inputs.use_zram && 'true' || 'false' }}
          Built-in KPM = ${{ inputs.use_kpm && 'true' || 'false' }}
          KPatch-Next Support = true</pre>
          Change Log: 
          <pre>${INPUT_CHANGE_LOG}
          </pre>
          
          Download: <a href="https://t.me/UnofficialReSukiSUGKI">View In Channel</a>

          Note: The "commit" here refers to ReSukiSU's commit, not this repository's.
          EOF
          )

          curl -s "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d message_thread_id="${message_thread_id}" \
            -d parse_mode="HTML" \
            --data-urlencode text="${TEXT}"